export const TOGGLE_EXPLORER = "TOGGLE_EXPLORER";
export const SET_COORDINATES = "SET_COORDINATES";
export const SET_LOCATIONS = "SET_LOCATIONS";
export const SET_LOCATION_LINK = "SET_LOCATION_LINK";
export const SET_LOADING = "SET_LOADING";
export const TOGGLE_EXPLORER_WITH_PAYLOAD = "TOGGLE_EXPLORER_WITH_PAYLOAD";
export const SET_MAP_CENTER = "SET_MAP_CENTER";
